### ISSUE TITLE
Digitally sign full generated PDF documents

### ISSUE THREAD

**Issue by stefanb** [MeetPlan/MeetPlanBackend#7]
Currently the generated PDFs are intended for printing onto the paper templates.

It would be useful to generate the full document with the background template(eg, not just in debug mode to test field placements as now)
https://github.com/MeetPlan/MeetPlanBackend/blob/a195576e17e13ffd67f9a1459c132a056e534f04/httphandlers/grades.go#L812-L818
- with digital signature with school certificate (on file or in HSM) AND/OR
- allowing teachers AND principals to sign them locally on their computers using existing software

**Comment by mytja** [comment]
> Currently the generated PDFs are intended for printing onto the paper templates.

"Spričevala" aka. ending certificates (or however it's said in English) are printed on paper templates, as THEY MUST BE. The templates are provided by DZS to schools, as not everybody has this high quality printers specifically for these documents. The law specifies the paper that must be used, the font etc. It's a really strict law to make sure there isn't any forgery of those official documents.

> It would be useful to generate the full document with the background template(eg, not just in debug mode to test field placements as now)

I agree. It would be useful and can simply be added.

> with digital signature with school certificate (on file or in HSM)

This should be pretty easy to implement, but we just need another package, as gopdf doesn't provide a way to sign the documents, only to encrypt them.
https://github.com/unidoc/unipdf-examples/blob/v3/signatures/pdf_sign_generate_keys.go

**Comment by stefanb** [comment]
Yes, it was not intended as a full replacement for the paper yet, but a step into that direction to help 
- users using them (sending them easily via email, upload forms) without first scanning them
- enabling recipients (high schools, companies, scholarship providers...) of those documents to verify them

**Comment by mytja** [comment]
![image](https://user-images.githubusercontent.com/52399966/181947289-d60b74e8-4d3e-4a65-ba02-aec0335f40d0.png)

**Comment by mytja** [comment]
One more document still needs to be digitally signed, so I'm keeping this open.
