### ISSUE TITLE
Consider license change to AGPL

### ISSUE THREAD

**Issue by stefanb** [MeetPlan/MeetPlanBackend#8]
See http://www.gnu.org/licenses/licenses.html#AGPL :
> The GNU Affero General Public License is based on the GNU GPL, but has an additional term to allow users who interact with the licensed software over a network to receive the source for that program. We recommend that people consider using the GNU AGPL for any software which will commonly be run over a network. The latest version is version 3.

Applies to all repositories with current GPL license, but is most critical to backend one (this one).

**Comment by mytja** [comment]
This seems way better. I'm no licensing expert, I just went with the one I knew the most, and that was GPL. Will change to it in following days.

**Comment by stefanb** [comment]
Make sure to get approval from each past code contributor.

**Comment by stefanb** [comment]
Of course you can also change to any other popular license (with approval from contributors).
The AGPL suggestion was just a proposed fix for the problem with currently chosen GPL.

**Comment by mytja** [comment]
> Make sure to get approval from each past code contributor.

I approve and I'm the only one who has ever contributed to this project.
